# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices =
    {
      crypted = {
        device = "/dev/disk/by-uuid/e6c2ffdd-62f5-494e-81d3-ea50b95abead";
        preLVM = true;
      };
    };

  fileSystems."/" =
    { device = "/dev/mapper/pool-root";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

	boot.initrd.postResumeCommands = lib.mkAfter ''
			mkdir /btrfs_tmp
			mount /dev/mapper/pool-root /btrfs_tmp
			if [[ -e /btrfs_tmp/@root ]]; then
					mkdir -p /btrfs_tmp/old_roots
					timestamp=$(date --date="@$(stat -c %Y /btrfs_tmp/@root)" "+%Y-%m-%-d_%H:%M:%S")
					mv /btrfs_tmp/@root "/btrfs_tmp/old_roots/$timestamp"
			fi

			delete_subvolume_recursively() {
					IFS=$'\n'
					for i in $(btrfs subvolume list -o "$1" | cut -f 9- -d ' '); do
							delete_subvolume_recursively "/btrfs_tmp/$i"
					done
					btrfs subvolume delete "$1"
			}

			for i in $(find /btrfs_tmp/old_roots/ -maxdepth 1 -mtime +30); do
					delete_subvolume_recursively "$i"
			done

			btrfs subvolume create /btrfs_tmp/@root
			umount /btrfs_tmp
		'';


  fileSystems."/nix" =
    { device = "/dev/mapper/pool-root";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/mapper/pool-root";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=@persist" ];
    };


  #fileSystems."/var/lib" =
  #  { device = "/dev/mapper/pool-root";
  #    fsType = "btrfs";
  #    options = [ "subvol=@var-lib" ];
  #  };

  #fileSystems."/var/cache" =
  #  { device = "/dev/mapper/pool-root";
  #    fsType = "btrfs";
  #    options = [ "subvol=@var-cache" ];
  #  };

  #fileSystems."/var/log" =
  #  { device = "/dev/mapper/pool-root";
  #    fsType = "btrfs";
  #    options = [ "subvol=@var-log" ];
  #  };

  #fileSystems."/var/tmp" =
  #  { device = "/dev/mapper/pool-root";
  #    fsType = "btrfs";
  #    options = [ "subvol=@var-tmp" ];
  #  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AFF9-072D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/29eeb359-f46b-4b36-a0cc-d829a97c63b3"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.printers = {
    ensurePrinters = [
      {
        name = "holdens_printer";
        description = "HP LaserJet CP1025NW";
        location = "Home";
        deviceUri = "dnssd://HP%20LaserJet%20CP1025nw._pdl-datastream._tcp.local/";
        model = "drv:///hp/hpcups.drv/hp-colorlaserjet_cp1025nw.ppd";
      }
    ];
  };
}
