# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModprobeConfig = "softdep psmouse pre: i2c_i801";
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices =
    {
      crypted = {
        device = "/dev/disk/by-uuid/e6c2ffdd-62f5-494e-81d3-ea50b95abead";
        preLVM = true;
      };
    };

  fileSystems."/" =
    { device = "/dev/mapper/pool-root";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  impermanence-wipe = {
    enable = true;
    device = "/dev/mapper/pool-root";
    retentionDays = 30;
  };


  fileSystems."/nix" =
    { device = "/dev/mapper/pool-root";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/mapper/pool-root";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=@persist" ];
    };

  fileSystems."/cache" =
    { device = "/dev/mapper/pool-root";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };


  #fileSystems."/var/lib" =
  #  { device = "/dev/mapper/pool-root";
  #    fsType = "btrfs";
  #    options = [ "subvol=@var-lib" ];
  #  };

  #fileSystems."/var/cache" =
  #  { device = "/dev/mapper/pool-root";
  #    fsType = "btrfs";
  #    options = [ "subvol=@var-cache" ];
  #  };

  #fileSystems."/var/log" =
  #  { device = "/dev/mapper/pool-root";
  #    fsType = "btrfs";
  #    options = [ "subvol=@var-log" ];
  #  };

  #fileSystems."/var/tmp" =
  #  { device = "/dev/mapper/pool-root";
  #    fsType = "btrfs";
  #    options = [ "subvol=@var-tmp" ];
  #  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AFF9-072D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/29eeb359-f46b-4b36-a0cc-d829a97c63b3"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Intel VA-API hardware video acceleration (for Moonlight, etc.)
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver  # VAAPI driver for Broadwell+ Intel GPUs
    ];
  };

  hardware.printers = {
    ensurePrinters = [
      {
        name = "holdens_printer";
        description = "HP LaserJet CP1025NW";
        location = "Home";
        deviceUri = "dnssd://HP%20LaserJet%20CP1025nw._pdl-datastream._tcp.local/";
        model = "HP/hp-laserjet_cp1025nw.ppd.gz";
      }
    ];
  };
}
